### ISSUE TITLE
[Style] DTO 생성자 포맷팅

### ISSUE THREAD

**Issue by Juser0** [Favor-Gift-Reminder/Favor-Server#1]
## 📋 이슈 내용
DTO (Data Transfer Object) 는 데이터 전송을 위한 클래스입니다.
JPA와 연관이 있는 부분은 Entity(Domain)에 대한 부분이기 때문에

DTO에서는 기본 생성자가 필요한 경우가 아니라면
@NoArgsConstructor(access = AccessLevel.PROTECTED) 대신
어노테이션만 사용하거나, 직접 기본생성자를 만들어주는 것이 좋습니다

[해당 어노테이션이 있는 DTO list]
User
- ProfileDto
- SignUpDto
- UserUpdatePasswordRequestDto
- UserUpdateRequestDto

anniversary
- AnniversaryRequestDto
- AnniversaryUpdateRequestDto

friend
- FriendUserRequestDto
- FriendRequestDto
- FriendUpdateRequestDto
- FriendResponseDto

gift
- GiftRequestDto
- GiftUpdateRequestDto

reminder
- ReminderRequestDto
- ReminderUpdateRequestDto

누락된 DTO 파일이 있는 지 확인해주시기 바랍니다

## ✅ 체크리스트
❌ 해당 DTO의 @NoArgsConstructor(access = AccessLevel.PROTECTED) 제거 후 테스트
❌ 오류 발생 시 accesslevel 없는 형태로 어노테이션 생성 혹은 기본 생성자 직접 구현

## 📚 레퍼런스

**Comment by nomatterjun** [comment]
와! 서버 첫 이슈!
👏👏👏

**Comment by nomatterjun** [comment]
test

**Comment by eunki96** [comment]
적용 했어유 '~'
