### ISSUE TITLE
[Fix] 리마인더 필터 년/월 입력값 유효한지 체크

### ISSUE THREAD

**Issue by eunki96** [Favor-Gift-Reminder/Favor-Server#14]
## 📋 이슈 내용
- 리마인더 년/월 필터 -> 년/월 입력값 유효한지 체크하는 예외처리 추가
![20230421163125](https://user-images.githubusercontent.com/114793764/233573493-34bee869-dcc7-4840-93de-ebad0028e6f1.png)

## ✅ 체크리스트
- [ ] userService.readReminderListByFMonthAndYear
- [ ] year과 month에 잘못된 값이 들어오면 400 반환
![20230421163549](https://user-images.githubusercontent.com/114793764/233573177-862e72da-ce06-491d-8a97-5c5fab72e143.png)
![20230421163558](https://user-images.githubusercontent.com/114793764/233573196-ad7101d9-20c2-46b7-a3a6-74309d22709e.png)

**Comment by Juser0** [comment]
이슈에서의 할당은 진행할 사람(해당 이슈는 형이 진행했으니 형을 assignee로) 을 지정하는 거고
PR에서 reviewer랑 assignee를 각자로 지정 (코드 안짠 사람이 코드 보고 리뷰 & merge) 하는 식으로 가는거야!

여기서는 그래서 assignee가 형인거지!

**Comment by eunki96** [comment]
> 이슈에서의 할당은 진행할 사람(해당 이슈는 형이 진행했으니 형을 assignee로) 을 지정하는 거고 PR에서 reviewer랑 assignee를 각자로 지정 (코드 안짠 사람이 코드 보고 리뷰 & merge) 하는 식으로 가는거야!
> 
> 여기서는 그래서 assignee가 형인거지!

------------------------------------------------------------------

오케이! 앞으로 그렇게 작성할게
