### ISSUE TITLE
[Style] Logging tools 통일

### ISSUE THREAD

**Issue by Juser0** [Favor-Gift-Reminder/Favor-Server#28]
## 📋 이슈 내용
현재 Logging을 위한 도구들이 여러가지가 사용되고 있습니다
(gift - Log4j2 / userService - slf4j)

logging tool을 하나로 통일 (slf4j로 하기로 했으니 그걸로) 해서 적용하는 식으로 수정부탁드립니다

## ✅ 체크리스트
- [x] slf4j 어노테이션으로 로깅 툴 통일
- [x] 로깅 툴이 필요하지 않은 경우 해당 소스에서는 어노테이션 삭제

**Comment by eunki96** [comment]
확인했습니다
