### ISSUE TITLE
[Docs] README.md 업데이트

### ISSUE THREAD

**Issue by Juser0** [Favor-Gift-Reminder/Favor-Server#7]
## 📋 이슈 내용
README.md의 내용을 업데이트해야합니다

- ERD 업데이트
현재의 README에 있는 ERD의 내용 중 변경된 사항에 대한 부분을 적용하여 새 이미지로 업데이트하는 작업이 필요합니다

- API 명세서 업데이트
현재의 README에 있는 내용처럼 넣어도 좋고, swagger에서 보이는 내용을 캡처하여 넣어도 좋습니다.
**어떤 방식이던 업데이트를 진행하거나, 해당하는 내용을 아예 삭제해도 괜찮습니다**
(API 명세는 swagger에 있기 때문에 업데이트가 곤란한 경우 굳이 넣지 않아도 괜찮을 듯 합니다)

- API 요청 응답 관련 내용 추가 **(optional)**
현xx재의 API 요청 결과의 형태를 보여주는 설명이 없습니다
성공 시 - 코드, 메시지, http 상태, dto(있는 경우)
실패 시 - 코드, 메시지, http 상태
이런 내용을 보여줌으로서 API를 실행한 결과를 어떻게 활용할 수 있는 지 프론트엔드에서 파악할 수 있도록 하면 좋을 것 같습니다

- 커밋, 브랜치, PR 컨벤션 정의 **(optional)**
협업에서 사용되는 여러 규칙들을 README에 적용하는 것도 좋아보입니다
만약, 해당 내용이 들어있지 않다면 따로 규칙을 적어서 검증하는 작업으로 대체할 수도 있습니다

- 개발 인원 명시 **(optional)**
참여자에 대한 정보를 넣어주는 것도 나쁘지는 않을 것 같습니다
만약 추가하는 경우, .github 의 에셋을 참고하면 될 것 같습니다

## ✅ 체크리스트
> 진행해야 할 사항들
- [ ] ERD 업데이트
- [ ] API 명세서 업데이트
- [ ] API 요청 응답 관련 내용 추가
- [ ] 커밋, 브랜치, PR 컨벤션 정의
- [ ] 개발 인원 명시

## 📚 레퍼런스
https://github.com/susanghan/cafehub-spring 의 readme file

**Comment by eunki96** [comment]
04.26 중간고사 종료 후 예정임
